name: Upload GPN Fahrplan

on:
  push:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v4
      with:
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: mkdir out
    - name: Prepare GPN Fahrplan
      run: python3 schedule_gpn.py
    - name: Minio Deploy
      uses: mamal72/minio-perfect-deploy-action@c672ba4a8b7d457edea227f1bf0d5b60d69079f2
      with:
        endpoint: https://s3.margau.net
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        bucket: 'gpn-fahrplan'
        source_dir: './out'
        target_dir: '/'
      # save out as artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gpn-fahrplan
        path: out
